#20 Student eliminated correctly
proyecto-arima/webapp pull request #24
Opened 2024-08-19 23:35 UTC by IgnacioG2000

2024-08-20 00:42 UTC, aleeherasimiuk requested changes

2024-08-20 00:42 UTC, aleeherasimiuk commented on src/pages/courses/StudentLinkingPage.tsx
> +    email: 'nachoestudiante2@gmail.com',
Sacar esto, dejarlo vacío

2024-08-20 00:42 UTC, aleeherasimiuk commented on src/pages/courses/StudentLinkingPage.tsx
> +      dispatch(removeStudentFromCourse({ courseId, userId }));
No hace falta hacer nada en redux

2024-08-20 00:42 UTC, aleeherasimiuk commented on src/redux/slices/courses.ts
>  })
No entiendo esto, no tendría que hacer falta

2024-10-17 22:43 UTC, Matiassgg commented
Ya esta en

https://github.com/proyecto-arima/webapp/blob/e4e606fb31accc94022efc4ce617c9762dfcddbc/src/pages/courses/StudentLinkingPage.tsx#L119

2024-10-17 22:43 UTC, closed without merging